Use Empy 3
ArduPilot fails to build with Empy 4:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/nix/store/handws5bj8l411asgs68s3bj8f05qnn5-python3-3.10.14/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/build/source/modules/DroneCAN/dronecan_dsdlc/dronecan_dsdlc.py", line 118, in expand_message
    output = em.expand(msg_header_template, get_empy_env_broadcast(msg))
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 5961, in expand
    result = interp.expand(data, locals, name, dispatcher=None)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 4681, in expand
    self.string(data, locals, dispatcher)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 4830, in string
    while not self.safe(scanner, True, locals, dispatcher):
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 4862, in safe
    if dispatcher():
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 4843, in safe
    return self.parse(scanner, locals)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 4870, in parse
    token = scanner.one()
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 3999, in one
    token.scan(self)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 2648, in scan
    self.subscan(scanner, self.type)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 2664, in subscan
    token = scanner.one()
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 3999, in one
    token.scan(self)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 2648, in scan
    self.subscan(scanner, self.type)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 2664, in subscan
    token = scanner.one()
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 3999, in one
    token.scan(self)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 2648, in scan
    self.subscan(scanner, self.type)
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 2664, in subscan
    token = scanner.one()
  File "/nix/store/gqf0agik1anj3d4rvfl40ljy0sz3yr93-python3.10-empy-4.1/lib/python3.10/site-packages/em.py", line 3995, in one
    raise ParseError("unknown markup sequence: `%s%s`%s" % (self.config.prefix, first, self.factory.addendum(first)))
em.ParseError: unknown markup sequence: `@)`; the `@)` markup has been removed, just use `)` instead
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/build/source/modules/DroneCAN/dronecan_dsdlc/dronecan_dsdlc.py", line 194, in <module>
    x = result.get()
  File "/nix/store/handws5bj8l411asgs68s3bj8f05qnn5-python3-3.10.14/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
em.ParseError: unknown markup sequence: `@)`; the `@)` markup has been removed, just use `)` instead